### ISSUE TITLE
error：go: go.mod file not found in current directory or any parent directory.

### ISSUE THREAD

**Issue by fish-2** [alex-user-go/gopack#1]
When I execute the command 【docker-compose up --abort-on-container-exit】, I get the following error，and Ahtens-storage file have notingCould you give me some advice，thanks！:

#-----------------------------------------------------------------------------------------------------------
gopack-main-golang-1  | go: downloading github.com/gin-contrib/sse v0.1.0
gopack-main-golang-1  | go: downloading github.com/mattn/go-isatty v0.0.14
gopack-main-golang-1  | go: downloading github.com/go-playground/validator/v10 v10.10.0
gopack-main-golang-1  | go: downloading github.com/pelletier/go-toml/v2 v2.0.1
gopack-main-golang-1  | go: downloading github.com/ugorji/go/codec v1.2.7
gopack-main-golang-1  | go: downloading google.golang.org/protobuf v1.28.0
gopack-main-golang-1  | go: downloading gopkg.in/yaml.v2 v2.4.0

gopack-main-golang-1  | go: go.mod file not found in current directory or any parent directory.
gopack-main-golang-1  |         'go get' is no longer supported outside a module.
gopack-main-golang-1  |         To build and install a command, use 'go install' with a version,
gopack-main-golang-1  |         like 'go install example.com/cmd@latest'
gopack-main-golang-1  |         For more information, see https://golang.org/doc/go-get-install-deprecation
gopack-main-golang-1  |         or run 'go help get' or 'go help install'.
gopack-main-golang-1 exited with code 1
#---------------------------------------------------------------------

and this is my goget.sh
#------------------------------------------------
#!/bin/bash
go get github.com/gin-gonic/gin@v1.8.1;
#--------------------------------------------------

I try to fix goget.sh like： go install github.com/gin-gonic/gin@v1.8.1;
then I get error：package github.com/gin-gonic/gin is not a main package

**Comment by alex-user-go** [comment]
Hello @fish-2!
Could you provide the list of packages you want to download?

**Comment by alex-user-go** [comment]
Hello @fish-2! 
Probably as the error said:
```
 'go get' is no longer supported outside a module.
```
I think it lacks a module initialization, so adding **RUN go mod init** to the Dockerfile might help. I'll check the issue later this week
